/*
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v3.1.2
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.org.openbanking.v3_1_2.accounts;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * BCA
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen", date = "2019-07-10T09:14:46.696896+02:00[Europe/Budapest]")
public class BCA {
    @JsonProperty("Overdraft")
    private Overdraft overdraft = null;

    @JsonProperty("ProductDetails")
    private ProductDetails productDetails = null;

    @JsonProperty("OtherFeesCharges")
    private List<BCAOtherFeesCharges> otherFeesCharges = null;

    @JsonProperty("CreditInterest")
    private CreditInterest creditInterest = null;

    public BCA overdraft(Overdraft overdraft) {
        this.overdraft = overdraft;
        return this;
    }

    /**
     * Get overdraft
     *
     * @return overdraft
     **/
    @JsonProperty("Overdraft")
    @ApiModelProperty(value = "")
    public Overdraft getOverdraft() {
        return overdraft;
    }

    public void setOverdraft(Overdraft overdraft) {
        this.overdraft = overdraft;
    }

    public BCA productDetails(ProductDetails productDetails) {
        this.productDetails = productDetails;
        return this;
    }

    /**
     * Get productDetails
     *
     * @return productDetails
     **/
    @JsonProperty("ProductDetails")
    @ApiModelProperty(value = "")
    public ProductDetails getProductDetails() {
        return productDetails;
    }

    public void setProductDetails(ProductDetails productDetails) {
        this.productDetails = productDetails;
    }

    public BCA otherFeesCharges(List<BCAOtherFeesCharges> otherFeesCharges) {
        this.otherFeesCharges = otherFeesCharges;
        return this;
    }

    public BCA addOtherFeesChargesItem(BCAOtherFeesCharges otherFeesChargesItem) {
        if (this.otherFeesCharges == null) {
            this.otherFeesCharges = new ArrayList<>();
        }
        this.otherFeesCharges.add(otherFeesChargesItem);
        return this;
    }

    /**
     * Contains details of fees and charges which are not associated with either Overdraft or features/benefits
     *
     * @return otherFeesCharges
     **/
    @JsonProperty("OtherFeesCharges")
    @ApiModelProperty(value = "Contains details of fees and charges which are not associated with either Overdraft or features/benefits")
    public List<BCAOtherFeesCharges> getOtherFeesCharges() {
        return otherFeesCharges;
    }

    public void setOtherFeesCharges(List<BCAOtherFeesCharges> otherFeesCharges) {
        this.otherFeesCharges = otherFeesCharges;
    }

    public BCA creditInterest(CreditInterest creditInterest) {
        this.creditInterest = creditInterest;
        return this;
    }

    /**
     * Get creditInterest
     *
     * @return creditInterest
     **/
    @JsonProperty("CreditInterest")
    @ApiModelProperty(value = "")
    public CreditInterest getCreditInterest() {
        return creditInterest;
    }

    public void setCreditInterest(CreditInterest creditInterest) {
        this.creditInterest = creditInterest;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        BCA BCA = (BCA) o;
        return Objects.equals(this.overdraft, BCA.overdraft) &&
                Objects.equals(this.productDetails, BCA.productDetails) &&
                Objects.equals(this.otherFeesCharges, BCA.otherFeesCharges) &&
                Objects.equals(this.creditInterest, BCA.creditInterest);
    }

    @Override
    public int hashCode() {
        return Objects.hash(overdraft, productDetails, otherFeesCharges, creditInterest);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class BCA {\n");

        sb.append("    overdraft: ").append(toIndentedString(overdraft)).append("\n");
        sb.append("    productDetails: ").append(toIndentedString(productDetails)).append("\n");
        sb.append("    otherFeesCharges: ").append(toIndentedString(otherFeesCharges)).append("\n");
        sb.append("    creditInterest: ").append(toIndentedString(creditInterest)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}

