/*
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v3.1.2
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.org.openbanking.v3_1_2.accounts;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Specifies the status of account resource in code form.
 */
public enum OBAccountStatus1Code {

    DELETED("Deleted"),

    DISABLED("Disabled"),

    ENABLED("Enabled"),

    PENDING("Pending"),

    PROFORMA("ProForma");

    private String value;

    OBAccountStatus1Code(String value) {
        this.value = value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }

    @JsonCreator
    public static OBAccountStatus1Code fromValue(String text) {
        for (OBAccountStatus1Code b : OBAccountStatus1Code.values()) {
            if (String.valueOf(b.value).equals(text)) {
                return b;
            }
        }
        throw new IllegalArgumentException("Unexpected value '" + text + "'");
    }
}

