/*
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v3.1.2
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.org.openbanking.v3_1_2.accounts;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Fee/Charge Type
 */
public enum OBFeeType1Code {

    FEPF("FEPF"),

    FTOT("FTOT"),

    FYAF("FYAF"),

    FYAM("FYAM"),

    FYAQ("FYAQ"),

    FYCP("FYCP"),

    FYDB("FYDB"),

    FYMI("FYMI"),

    FYXX("FYXX");

    private String value;

    OBFeeType1Code(String value) {
        this.value = value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }

    @JsonCreator
    public static OBFeeType1Code fromValue(String text) {
        for (OBFeeType1Code b : OBFeeType1Code.values()) {
            if (String.valueOf(b.value).equals(text)) {
                return b;
            }
        }
        throw new IllegalArgumentException("Unexpected value '" + text + "'");
    }
}

