/*
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v3.1.2
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.org.openbanking.v3_1_2.accounts;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * How frequently the fee/charge is applied to the account
 */
public enum OBFeeFrequency1Code2 {

    FEAC("FEAC"),

    FEAO("FEAO"),

    FECP("FECP"),

    FEDA("FEDA"),

    FEHO("FEHO"),

    FEI("FEI"),

    FEMO("FEMO"),

    FEOA("FEOA"),

    FEOT("FEOT"),

    FEPC("FEPC"),

    FEPH("FEPH"),

    FEPO("FEPO"),

    FEPS("FEPS"),

    FEPT("FEPT"),

    FEPTA("FEPTA"),

    FEPTP("FEPTP"),

    FEQU("FEQU"),

    FESM("FESM"),

    FEST("FEST"),

    FEWE("FEWE"),

    FEYE("FEYE");

    private String value;

    OBFeeFrequency1Code2(String value) {
        this.value = value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }

    @JsonCreator
    public static OBFeeFrequency1Code2 fromValue(String text) {
        for (OBFeeFrequency1Code2 b : OBFeeFrequency1Code2.values()) {
            if (String.valueOf(b.value).equals(text)) {
                return b;
            }
        }
        throw new IllegalArgumentException("Unexpected value '" + text + "'");
    }
}

