/*
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v3.1.2
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.org.openbanking.v3_1_2.accounts;

import com.fasterxml.jackson.annotation.*;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.validation.constraints.Size;
import java.util.Objects;

/**
 * Product details associated with the Account
 */
@ApiModel(description = "Product details associated with the Account")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen", date = "2019-07-10T09:14:46.696896+02:00[Europe/Budapest]")
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class OBReadProduct2DataProduct {
    @JsonProperty("SecondaryProductId")
    private String secondaryProductId = null;

    @JsonProperty("MarketingStateId")
    private String marketingStateId = null;

    @JsonProperty("OtherProductType")
    private OBReadProduct2DataOtherProductType otherProductType = null;

    @JsonProperty("BCA")
    private BCA BCA = null;

    @JsonProperty("AccountId")
    private String accountId = null;

    @JsonProperty("ProductName")
    private String productName = null;
    @JsonProperty("ProductType")
    private ProductTypeEnum productType = null;
    @JsonProperty("ProductId")
    private String productId = null;
    @JsonProperty("PCA")
    private PCA PCA = null;

    public OBReadProduct2DataProduct secondaryProductId(String secondaryProductId) {
        this.secondaryProductId = secondaryProductId;
        return this;
    }

    /**
     * Any secondary Identification which  supports Product Identifier to uniquely identify the current account banking products.
     *
     * @return secondaryProductId
     **/
    @JsonProperty("SecondaryProductId")
    @ApiModelProperty(value = "Any secondary Identification which  supports Product Identifier to uniquely identify the current account banking products.")
    @Size(min = 1, max = 70)
    public String getSecondaryProductId() {
        return secondaryProductId;
    }

    public void setSecondaryProductId(String secondaryProductId) {
        this.secondaryProductId = secondaryProductId;
    }

    public OBReadProduct2DataProduct marketingStateId(String marketingStateId) {
        this.marketingStateId = marketingStateId;
        return this;
    }

    /**
     * Unique and unambiguous identification of a  Product Marketing State.
     *
     * @return marketingStateId
     **/
    @JsonProperty("MarketingStateId")
    @ApiModelProperty(value = "Unique and unambiguous identification of a  Product Marketing State.")
    @Size(min = 1, max = 35)
    public String getMarketingStateId() {
        return marketingStateId;
    }

    public void setMarketingStateId(String marketingStateId) {
        this.marketingStateId = marketingStateId;
    }

    public OBReadProduct2DataProduct otherProductType(OBReadProduct2DataOtherProductType otherProductType) {
        this.otherProductType = otherProductType;
        return this;
    }

    /**
     * Get otherProductType
     *
     * @return otherProductType
     **/
    @JsonProperty("OtherProductType")
    @ApiModelProperty(value = "")
    public OBReadProduct2DataOtherProductType getOtherProductType() {
        return otherProductType;
    }

    public void setOtherProductType(OBReadProduct2DataOtherProductType otherProductType) {
        this.otherProductType = otherProductType;
    }

    public OBReadProduct2DataProduct BCA(BCA BCA) {
        this.BCA = BCA;
        return this;
    }

    /**
     * Get BCA
     *
     * @return BCA
     **/
    @JsonProperty("BCA")
    @ApiModelProperty(value = "")
    public BCA getBCA() {
        return BCA;
    }

    public void setBCA(BCA BCA) {
        this.BCA = BCA;
    }

    public OBReadProduct2DataProduct accountId(String accountId) {
        this.accountId = accountId;
        return this;
    }

    /**
     * Account Identification of the customer for Product Details
     *
     * @return accountId
     **/
    @JsonProperty("AccountId")
    @ApiModelProperty(value = "Account Identification of the customer for Product Details")
    @Size(min = 1, max = 40)
    public String getAccountId() {
        return accountId;
    }

    public void setAccountId(String accountId) {
        this.accountId = accountId;
    }

    public OBReadProduct2DataProduct productName(String productName) {
        this.productName = productName;
        return this;
    }

    /**
     * The name of the Product used for marketing purposes from a customer perspective. I.e. what the customer would recognise.
     *
     * @return productName
     **/
    @JsonProperty("ProductName")
    @ApiModelProperty(value = "The name of the Product used for marketing purposes from a customer perspective. I.e. what the customer would recognise.")
    @Size(min = 1, max = 350)
    public String getProductName() {
        return productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public OBReadProduct2DataProduct productType(ProductTypeEnum productType) {
        this.productType = productType;
        return this;
    }

    /**
     * Product type : Personal Current Account, Business Current Account
     *
     * @return productType
     **/
    @JsonProperty("ProductType")
    @ApiModelProperty(value = "Product type : Personal Current Account, Business Current Account")
    public ProductTypeEnum getProductType() {
        return productType;
    }

    public void setProductType(ProductTypeEnum productType) {
        this.productType = productType;
    }

    public OBReadProduct2DataProduct productId(String productId) {
        this.productId = productId;
        return this;
    }

    /**
     * The unique ID that has been internally assigned by the financial institution to each of the current account banking products they market to their retail and/or small to medium enterprise (SME) customers.
     *
     * @return productId
     **/
    @JsonProperty("ProductId")
    @ApiModelProperty(value = "The unique ID that has been internally assigned by the financial institution to each of the current account banking products they market to their retail and/or small to medium enterprise (SME) customers.")
    @Size(min = 1, max = 40)
    public String getProductId() {
        return productId;
    }

    public void setProductId(String productId) {
        this.productId = productId;
    }

    public OBReadProduct2DataProduct PCA(PCA PCA) {
        this.PCA = PCA;
        return this;
    }

    /**
     * Get PCA
     *
     * @return PCA
     **/
    @JsonProperty("PCA")
    @ApiModelProperty(value = "")
    public PCA getPCA() {
        return PCA;
    }

    public void setPCA(PCA PCA) {
        this.PCA = PCA;
    }

    @Override
    public int hashCode() {
        return Objects.hash(secondaryProductId, marketingStateId, otherProductType, BCA, accountId, productName, productType, productId, PCA);
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        OBReadProduct2DataProduct obReadProduct2DataProduct = (OBReadProduct2DataProduct) o;
        return Objects.equals(this.secondaryProductId, obReadProduct2DataProduct.secondaryProductId) &&
                Objects.equals(this.marketingStateId, obReadProduct2DataProduct.marketingStateId) &&
                Objects.equals(this.otherProductType, obReadProduct2DataProduct.otherProductType) &&
                Objects.equals(this.BCA, obReadProduct2DataProduct.BCA) &&
                Objects.equals(this.accountId, obReadProduct2DataProduct.accountId) &&
                Objects.equals(this.productName, obReadProduct2DataProduct.productName) &&
                Objects.equals(this.productType, obReadProduct2DataProduct.productType) &&
                Objects.equals(this.productId, obReadProduct2DataProduct.productId) &&
                Objects.equals(this.PCA, obReadProduct2DataProduct.PCA);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class OBReadProduct2DataProduct {\n");

        sb.append("    secondaryProductId: ").append(toIndentedString(secondaryProductId)).append("\n");
        sb.append("    marketingStateId: ").append(toIndentedString(marketingStateId)).append("\n");
        sb.append("    otherProductType: ").append(toIndentedString(otherProductType)).append("\n");
        sb.append("    BCA: ").append(toIndentedString(BCA)).append("\n");
        sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
        sb.append("    productName: ").append(toIndentedString(productName)).append("\n");
        sb.append("    productType: ").append(toIndentedString(productType)).append("\n");
        sb.append("    productId: ").append(toIndentedString(productId)).append("\n");
        sb.append("    PCA: ").append(toIndentedString(PCA)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Product type : Personal Current Account, Business Current Account
     */
    public enum ProductTypeEnum {
        BUSINESSCURRENTACCOUNT("BusinessCurrentAccount"),

        COMMERCIALCREDITCARD("CommercialCreditCard"),

        OTHER("Other"),

        PERSONALCURRENTACCOUNT("PersonalCurrentAccount"),

        SMELOAN("SMELoan");

        private String value;

        ProductTypeEnum(String value) {
            this.value = value;
        }

        @JsonCreator
        public static ProductTypeEnum fromValue(String text) {
            for (ProductTypeEnum b : ProductTypeEnum.values()) {
                if (String.valueOf(b.value).equals(text)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + text + "'");
        }

        @Override
        @JsonValue
        public String toString() {
            return String.valueOf(value);
        }
    }
}

