/*
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v3.1.2
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.org.openbanking.v3_1_2.accounts;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import javax.validation.constraints.Size;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * OBReadBalance1Data
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen", date = "2019-07-10T09:14:46.696896+02:00[Europe/Budapest]")
public class OBReadBalance1Data {
    @JsonProperty("Balance")
    private List<OBReadBalance1DataBalance> balance = null;

    public OBReadBalance1Data balance(List<OBReadBalance1DataBalance> balance) {
        this.balance = balance;
        return this;
    }

    public OBReadBalance1Data addBalanceItem(OBReadBalance1DataBalance balanceItem) {
        if (this.balance == null) {
            this.balance = new ArrayList<>();
        }
        this.balance.add(balanceItem);
        return this;
    }

    /**
     * Get balance
     *
     * @return balance
     **/
    @JsonProperty("Balance")
    @ApiModelProperty(value = "")
    @Size(min = 1)
    public List<OBReadBalance1DataBalance> getBalance() {
        return balance;
    }

    public void setBalance(List<OBReadBalance1DataBalance> balance) {
        this.balance = balance;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        OBReadBalance1Data obReadBalance1Data = (OBReadBalance1Data) o;
        return Objects.equals(this.balance, obReadBalance1Data.balance);
    }

    @Override
    public int hashCode() {
        return Objects.hash(balance);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class OBReadBalance1Data {\n");

        sb.append("    balance: ").append(toIndentedString(balance)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}

