/*
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v3.1.2
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.org.openbanking.v3_1_2.accounts;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * OBReadParty3Data
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen", date = "2019-07-10T09:14:46.696896+02:00[Europe/Budapest]")
public class OBReadParty3Data {
    @JsonProperty("Party")
    private List<OBParty2> party = null;

    public OBReadParty3Data party(List<OBParty2> party) {
        this.party = party;
        return this;
    }

    public OBReadParty3Data addPartyItem(OBParty2 partyItem) {
        if (this.party == null) {
            this.party = new ArrayList<>();
        }
        this.party.add(partyItem);
        return this;
    }

    /**
     * Get party
     *
     * @return party
     **/
    @JsonProperty("Party")
    @ApiModelProperty(value = "")
    public List<OBParty2> getParty() {
        return party;
    }

    public void setParty(List<OBParty2> party) {
        this.party = party;
    }

    @Override
    public int hashCode() {
        return Objects.hash(party);
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        OBReadParty3Data obReadParty3Data = (OBReadParty3Data) o;
        return Objects.equals(this.party, obReadParty3Data.party);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class OBReadParty3Data {\n");

        sb.append("    party: ").append(toIndentedString(party)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}

