/*
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v3.1.2
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.org.openbanking.v3_1_2.accounts;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.validation.constraints.Size;
import java.math.BigDecimal;
import java.util.Objects;

/**
 * Set of elements used to provide details of a fee for the statement resource.
 */
@ApiModel(description = "Set of elements used to provide details of a fee for the statement resource.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen", date = "2019-07-10T09:14:46.696896+02:00[Europe/Budapest]")
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class OBStatement2StatementFee {
    @JsonProperty("Type")
    private String type = null;

    @JsonProperty("Description")
    private String description = null;

    @JsonProperty("Rate")
    private BigDecimal rate = null;

    @JsonProperty("Amount")
    private OBActiveOrHistoricCurrencyAndAmount4 amount = null;

    @JsonProperty("Frequency")
    private String frequency = null;

    @JsonProperty("CreditDebitIndicator")
    private OBCreditDebitCode0 creditDebitIndicator = null;

    @JsonProperty("RateType")
    private String rateType = null;

    public OBStatement2StatementFee type(String type) {
        this.type = type;
        return this;
    }

    /**
     * Fee type, in a coded form.
     *
     * @return type
     **/
    @JsonProperty("Type")
    @ApiModelProperty(value = "Fee type, in a coded form.")
    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public OBStatement2StatementFee description(String description) {
        this.description = description;
        return this;
    }

    /**
     * Description that may be available for the statement fee.
     *
     * @return description
     **/
    @JsonProperty("Description")
    @ApiModelProperty(value = "Description that may be available for the statement fee.")
    @Size(min = 1, max = 128)
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public OBStatement2StatementFee rate(BigDecimal rate) {
        this.rate = rate;
        return this;
    }

    /**
     * Rate charged for Statement Fee (where it is charged in terms of a rate rather than an amount)
     *
     * @return rate
     **/
    @JsonProperty("Rate")
    @ApiModelProperty(value = "Rate charged for Statement Fee (where it is charged in terms of a rate rather than an amount)")
    public BigDecimal getRate() {
        return rate;
    }

    public void setRate(BigDecimal rate) {
        this.rate = rate;
    }

    public OBStatement2StatementFee amount(OBActiveOrHistoricCurrencyAndAmount4 amount) {
        this.amount = amount;
        return this;
    }

    /**
     * Get amount
     *
     * @return amount
     **/
    @JsonProperty("Amount")
    @ApiModelProperty(value = "")
    public OBActiveOrHistoricCurrencyAndAmount4 getAmount() {
        return amount;
    }

    public void setAmount(OBActiveOrHistoricCurrencyAndAmount4 amount) {
        this.amount = amount;
    }

    public OBStatement2StatementFee frequency(String frequency) {
        this.frequency = frequency;
        return this;
    }

    /**
     * How frequently the fee is applied to the Account.
     *
     * @return frequency
     **/
    @JsonProperty("Frequency")
    @ApiModelProperty(value = "How frequently the fee is applied to the Account.")
    public String getFrequency() {
        return frequency;
    }

    public void setFrequency(String frequency) {
        this.frequency = frequency;
    }

    public OBStatement2StatementFee creditDebitIndicator(OBCreditDebitCode0 creditDebitIndicator) {
        this.creditDebitIndicator = creditDebitIndicator;
        return this;
    }

    /**
     * Get creditDebitIndicator
     *
     * @return creditDebitIndicator
     **/
    @JsonProperty("CreditDebitIndicator")
    @ApiModelProperty(value = "")
    public OBCreditDebitCode0 getCreditDebitIndicator() {
        return creditDebitIndicator;
    }

    public void setCreditDebitIndicator(OBCreditDebitCode0 creditDebitIndicator) {
        this.creditDebitIndicator = creditDebitIndicator;
    }

    public OBStatement2StatementFee rateType(String rateType) {
        this.rateType = rateType;
        return this;
    }

    /**
     * Description that may be available for the statement fee rate type.
     *
     * @return rateType
     **/
    @JsonProperty("RateType")
    @ApiModelProperty(value = "Description that may be available for the statement fee rate type.")
    public String getRateType() {
        return rateType;
    }

    public void setRateType(String rateType) {
        this.rateType = rateType;
    }

    @Override
    public int hashCode() {
        return Objects.hash(type, description, rate, amount, frequency, creditDebitIndicator, rateType);
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        OBStatement2StatementFee obStatement2StatementFee = (OBStatement2StatementFee) o;
        return Objects.equals(this.type, obStatement2StatementFee.type) &&
                Objects.equals(this.description, obStatement2StatementFee.description) &&
                Objects.equals(this.rate, obStatement2StatementFee.rate) &&
                Objects.equals(this.amount, obStatement2StatementFee.amount) &&
                Objects.equals(this.frequency, obStatement2StatementFee.frequency) &&
                Objects.equals(this.creditDebitIndicator, obStatement2StatementFee.creditDebitIndicator) &&
                Objects.equals(this.rateType, obStatement2StatementFee.rateType);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class OBStatement2StatementFee {\n");

        sb.append("    type: ").append(toIndentedString(type)).append("\n");
        sb.append("    description: ").append(toIndentedString(description)).append("\n");
        sb.append("    rate: ").append(toIndentedString(rate)).append("\n");
        sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
        sb.append("    frequency: ").append(toIndentedString(frequency)).append("\n");
        sb.append("    creditDebitIndicator: ").append(toIndentedString(creditDebitIndicator)).append("\n");
        sb.append("    rateType: ").append(toIndentedString(rateType)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}

